import type { Metadata } from "next";
import "./globals.css";
import { Ancizar_Sans } from "next/font/google";

const ancizar = Ancizar_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ancizar.variable}>
      <body className="font-sans">
        {children}
      </body>
    </html>
  );
}
