import type { Metadata } from "next";
import "./globals.css";
import { Quicksand } from "next/font/google";
import { Navbar } from "../components/Navbar";
import Footer from "@/components/Footer";
import { loadCategories } from "@/lib/data/categoryMapper";

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-sans",
  fallback: ["Arial", "sans-serif"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Blog Site",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await loadCategories();
  return (
    <html lang="en" className={quicksand.variable}>
      <body>
        <Navbar categories={categories} />
        <main className="mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
