import type { Metadata } from "next";
import "./globals.css";
import { Quicksand } from "next/font/google";
import { Navbar } from "../components/Navbar"; // ✅ import globally

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-sans",
  fallback: ["Arial", "sans-serif"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={quicksand.variable}>
      <body>
        <Navbar />
        <main className="max-w-[90%] mx-auto">{children}</main>
      </body>
    </html>
  );
}
